spring:
  application:
    name: tourApp

  datasource:
    url: jdbc:postgresql://localhost:5432/tourDB
    username: user
    password: pasword
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: ALWAYS
      schema-locations:
        - 'classpath:shema.sql'
        - 'classpath:triggers.sql'
        - 'classpath:functions.sql'
        -  'classpath:procedures.sql'
      encoding: 'UTF-8'

backup:
  path: backups

jwt:
  secret: L54OZNDg9xvTuB+kGTxzS+8QgZ6X6mQ0eGiM9MkYKPY=
